include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for the PuGongYing VPN
LUCI_DEPENDS:=+pgyvpn-mt7621 +pgyvpn-ipq5018 +luci-base +luci-mod-system

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
